name: vicguzher

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  issue-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar sobre el nuevo issue
        run: echo "Se ha creado un nuevo issue"

