name: vicguzher

on:
  workflow_dispatch:
  issues:
    types: 
      - opened
      - edited


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo el artefacto
        run: |
          chmod +x gradlew
          ./gradlew assemble

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Ejecutando pruebas
        run: |
          chmod +x gradlew
          ./gradlew test
